// Kart "resmi" için emoji yer tutucuları (yalnız görsel). Kart değerleri content/ JSON'larından gelir.
const ART: Record<string, string> = {
  'quick-strike': '⚡',
  absoluteness: '🔰',
  intimidate: '😠',
  valor: '✨',
  'power-strike': '🔨',
  slash: '⚔️',
  gain: '💪',
  'leg-cutting': '🦵',
  berserker: '😤',
  'iron-skin': '🛡️',
  cleave: '🪓',
  'howling-sword': '🌪️',
  'wall-of-iron': '🧱',
  'sword-dancing': '🌀',
  'hell-blade': '💥',
  'minor-healing': '💚',
  evade: '💨',
  'scaled-skin': '🐍',
  stab: '🗡️',
  stealth: '🌑',
  thrust: '🔪',
  blinding: '👁️',
  spike: '📌',
  'critical-point': '🎯',
  'beast-hiding': '🐾',
  'poison-arrow': '☠️',
  'perfect-arrow': '🏹',
  'multiple-shot': '🎇',
  viper: '🐍',
  'blinding-strafe': '💫',
  'arrow-shower': '🌧️',
  'power-shot': '☄️',
  // Faz 2b · Mage (Donma hazırlığı → Ateş bitirici)
  freeze: '❄️',
  burn: '🔥',
  chill: '🌬️',
  'fire-ball': '🧨',
  'frozen-armor': '🧊',
  lightning: '🌩️',
  'ice-comet': '☄️',
  'freezing-distance': '🌨️',
  incineration: '🌋',
  'meteor-fall': '🌠',
  // Faz 2b · Priest (iyileşme, Zayıflık, Parasite)
  healing: '💗',
  malice: '😈',
  massive: '🪨',
  parasite: '🦠',
  helis: '🌟',
  judgement: '⚖️',
  'great-healing': '💖',
  torment: '😖',
  'superior-parasite': '🧬',
  'complete-heal': '🕊️',
};

export const cardArt = (id: string): string => ART[id] ?? '🂠';
