// Kart "resmi" için emoji yer tutucuları (yalnız görsel). Kart değerleri content/ JSON'larından gelir.
const ART: Record<string, string> = {
  'quick-strike': '⚡',
  absoluteness: '🔰',
  intimidate: '😠',
  valor: '✨',
  'power-strike': '🔨',
  slash: '⚔️',
  gain: '💪',
  'leg-cutting': '🦵',
  berserker: '😤',
  'iron-skin': '🛡️',
  cleave: '🪓',
  'howling-sword': '🌪️',
  'wall-of-iron': '🧱',
  'sword-dancing': '🌀',
  'hell-blade': '💥',
  'minor-healing': '💚',
  evade: '💨',
  'scaled-skin': '🐍',
  stab: '🗡️',
  stealth: '🌑',
  thrust: '🔪',
  blinding: '👁️',
  spike: '📌',
  'critical-point': '🎯',
  'beast-hiding': '🐾',
  'poison-arrow': '☠️',
  'perfect-arrow': '🏹',
  'multiple-shot': '🎇',
  viper: '🐍',
  'blinding-strafe': '💫',
  'arrow-shower': '🌧️',
  'power-shot': '☄️',
};

export const cardArt = (id: string): string => ART[id] ?? '🂠';
